server:
  port: 1234
spring:
  application:
    name: enrekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false