spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.3:3306/smbms?useUnicode=true&charsetEncoding=utf-8
    username: root
    password: 123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
